### ISSUE TITLE
Screen Freezes on "Perform MOK management" screen

### ISSUE THREAD

**Issue by JazzTech** [ValdikSS/Super-UEFIinSecureBoot-Disk#11]
I have an MSI X570 ACE motherboard with a 5950X processor and the latest MSI BIOS firmware loaded.

I am attempting to register the **ENROLL_THIS_KEY_IN_MOKMANAGER.cer** keys in MOK Manager.

With **SECURE BOOT**=**STANDARD** (Enabled) in the UEFI BIOS, I booted from a USB drive loaded with the **Super-UEFIinSecureBoot-Disk_v3** image.

 When my system boots up, I see the expected **Access Denied** error message. But when I get to the **Perform MOK management** screen and select **Enroll key from disk**, the screen freezes and I have to power down the PC to reboot. I can't get to the screen that shows the ENROLL_THIS_KEY_IN_MOKMANAGER.cer file selection to register the keys.

**Comment by ValdikSS** [comment]
Try https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/releases/tag/3-2

**Comment by JazzTech** [comment]
Hi, @ValdikSS - I have been using the MOK management with a pre-packaged tool (Ventoy on ventoy.net).

I would like to try out your fixes. Is there an easy way to merger your updates into the Ventoy boot partition?

**Comment by ValdikSS** [comment]
@JazzTech, you can unpack the image and copy over files in EFI/BOOT, namely bootx64.efi, grubx64.efi, mmx64.efi

**Comment by ValdikSS** [comment]
Should be fixed in the 3-4.

**Comment by Arcitec** [comment]
Solved: https://github.com/ventoy/Ventoy/issues/1243#issuecomment-1366812283
