### ISSUE TITLE
Is it possible to install this image on windows 10-11?

### ISSUE THREAD

**Issue by HighError** [ValdikSS/Super-UEFIinSecureBoot-Disk#12]
ENG: Is it possible to install this image on Windows 10-11 as a rEFInd in a hidden partition and NOT on a flash drive?
If so, how different is the installation?

RU: Можно ли установить этот образ на Windows 10-11 как rEFInd в скрытый раздел, а НЕ на флешку?
Если да, то насколько отличается установка?

**Comment by ValdikSS** [comment]
So you want to launch SUISDB from rEFInd, then SUISDB should launch Windows 10? That should be possible but sounds pointless. What exact issue do you encounter?

**Comment by HighError** [comment]
I have Windows and Kali linux systems installed.  It is not possible for me to use the standard grub, because the grub breaks the bios (the problem with my laptop)

**Comment by ValdikSS** [comment]
Why do you need grub or this disk at all then, if you have rEFInd already? If you want to keep Secure Boot enabled for some reason, you can enroll your own keys for Kali (if it's not signed, I don't know) into UEFI and sign rEFInd and Kali kernel with those keys.
