### ISSUE TITLE
Obsolete link and package name

### ISSUE THREAD

**Issue by Ricky-Tigg** [ValdikSS/Super-UEFIinSecureBoot-Disk#13]
Hello. At that platform [page](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk),  link "[_from Fedora_"](https://apps.fedoraproject.org/packages/shim-signed) is obsolete. that is the valid [link](https://apps.fedoraproject.org/#Packages) for _Packages_ section. As noticeable, a search against the package named _shim-signed_ won't  return match, therefore that package name too is obsolete.

**Comment by ValdikSS** [comment]
Yeah, Fedora broke their apps page several years ago.
Here's koji link: https://koji.fedoraproject.org/koji/packageinfo?packageID=15107

**Comment by ValdikSS** [comment]
Updated.

**Comment by Ricky-Tigg** [comment]
In page of that new link, at _Tags_, mention _f28-updates_ is obsolete.

**Comment by ValdikSS** [comment]
Yes, current version is called just shim
https://koji.fedoraproject.org/koji/packageinfo?packageID=14502
But what's used in this package is old shim-signed.
