### ISSUE TITLE
unsupported format

### ISSUE THREAD

**Issue by AlieZ777** [ValdikSS/Super-UEFIinSecureBoot-Disk#16]
surface pro 7，windows11，unsupported format
![c3c3f8b8eb7ce025a6beb2ca3b9a1d1](https://user-images.githubusercontent.com/31228933/168294561-e5849a9c-edcb-468a-aeab-cde467f0dfea.jpg)

**Comment by 3pichaxz0r** [comment]
I had the same issue on a surface laptop, you can enroll the hash from the efi binary instead and it works

**Comment by ValdikSS** [comment]
The certificate is already in DER format. I have a Surface 3 (not Pro), will try to boot it later, but if I recall correctly, everything worked fine earlier.
Maybe the certificate is not totally valid, but I doubt.

**Comment by ventoy** [comment]
@ValdikSS 
Some Ventoy users also have the same issue.

**Comment by chatmandu-uk** [comment]
> I had the same issue on a surface laptop, you can enroll the hash from the efi binary instead and it works

How do I do this?

**Comment by 3pichaxz0r** [comment]
> How do I do this?

you should have two options when enrolling, enroll from cert and enroll from hash. If you select the later you need to then select the efi binary you are trying to boot to which should be "grubx64.efi" provided you haven't customized this project

**Comment by chatmandu-uk** [comment]
Thanks. I got that working by trial and error.

**Comment by ValdikSS** [comment]
Could anybody affected by this bug take a photo of the file selection dialog inside shim?
Could it be that all the files are uppercased?

**Comment by ValdikSS** [comment]
New version contains MokManager from shim 15.4-5, which should fix this issue.
https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/releases/tag/3-3
