### ISSUE TITLE
Kali linux Secure boot

### ISSUE THREAD

**Issue by AnonymisedFellow** [ValdikSS/Super-UEFIinSecureBoot-Disk#19]
Hi, i have a laptop Aorus 17G XC and its my fifth day of trying to boot a live version of kali linux. I have tried every possible tutorial and and i cannot get trough. Right now im stuck at error: prohibited by secure boot policy in grub and have no idea what to do next. Ive read somewhere that you can help directly with the issue so ive decided to write here. I tried many manual fixes but lastly i tried ventoy with secure boot support enabled. It launches nicely and then when the grub shows up with the menu to start live or smth like that it just shows this "error: prohibited by secure boot policy". Have you got any clue what am i doing wrong?

**Comment by ValdikSS** [comment]
I suppose the following happens:
1. Kali Linux does not support Secure Boot (does not have signed loader and kernel), but still uses GRUB with Secure Boot support
2. You're trying to boot the image using Ventoy, which disables Secure Boot *validation*
3. GRUB of Kali Linux boots, detects enabled Secure Boot and applies its own module/configuration policy

There's nothing SUISBD could do other than spoof Secure Boot state, which is dumb.
There are two solutions:
1. Kali Linux developers should patch GRUB to disable Secure Boot support/disable policies
2. You can just disable Secure Boot.
