### ISSUE TITLE
Query: How to MBR-boot to grub2 without using special image?

### ISSUE THREAD

**Issue by steve6375** [ValdikSS/Super-UEFIinSecureBoot-Disk#2]
Could you also provide a g2ldr or core.img file in the download please or suggest a way in which  I can add this to an existing grub4dos USB drive without having to run linux and the .sh script, etc and overwite the PBR?  Thanks.

**Comment by ValdikSS** [comment]
There is core.img in `modules-source.zip` download file. To install GRUB2 loader in Windows, you can copy 446 MBR bytes and "empty" space after partition table and first partition using HEX editor, I guess.

**Comment by steve6375** [comment]
I cannot find it in Super-UEFIinSecureBoot-Disk_modules-source_v3.zip?
I dont mean the MBR\PBR, I mean the actual grub2 core file.

**Comment by ValdikSS** [comment]
It seems I didn't save it, since it's kind of temporary file. You can generate your own core.img with `kernel.img` and `boot.img` from `Super-UEFIinSecureBoot-Disk_modules-source_v3.zip` using 

`grub2-mkimage -d EFI/grub/i386-pc -v -C auto -O i386-pc --prefix '(,msdos1)/efi/grub' -o EFI/grub/i386-pc/core.img 'iso9660' 'fat' 'part_msdos' 'part_gpt' 'part_apple' 'biosdisk' 'xzio' 'gcry_crc'`

command

**Comment by steve6375** [comment]
Thanks, I tried saving LBA1-220 as core.img. The grub4dos kernel command loaded OK, it but it crashes on boot :-(
![image](https://user-images.githubusercontent.com/1469350/54437691-1866c700-472d-11e9-99ef-0d582ac880ac.png)
I don't have linux (and generally, trying to make a linux VM and then compile a source takes me about 3 days to figure out all the stuff I need to do to get it to work!). If you could include core.img in any future build it would be appreciated. Keep up the good work! It looks very useful.

**Comment by ValdikSS** [comment]
Try this: [core.zip](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/files/2971483/core.zip)
I'll include core.img into future builds.

**Comment by steve6375** [comment]
Works great! Thanks!
