### ISSUE TITLE
boot windows BIOS

### ISSUE THREAD

**Issue by llxiaoyuan** [ValdikSS/Super-UEFIinSecureBoot-Disk#22]
Hello.
First of all, thanks for creating this rep it's really helpful.

i want to asking about is there anyway to chainload a windows booted by BIOS in （if [ "${grub_platform}" == "efi" ]）？

when i use ntldr /bootmgr，i get error ：can't find  command 'ntldr'

**Comment by ValdikSS** [comment]
Hello, no, this is not possible.
