### ISSUE TITLE
Using grub-2.06-for-windows.zip, How do I apply your security bypass patches to chainloader, linux/linuxefi and shim？

### ISSUE THREAD

**Issue by 1457384613gh** [ValdikSS/Super-UEFIinSecureBoot-Disk#23]
Hi,
Above all, thanks for your great S-U-D.

## I've got a problem
https://ftp.gnu.org/gnu/grub/
What I use is [grub-2.06-for-windows.zip](https://ftp.gnu.org/gnu/grub/).
How do I apply your security bypass patches to chainloader, linux/linuxefi and shim？

Is there a `linux.mod`, `chain.mod` or `kernel.img` patched with security bypass?

**Comment by 1457384613gh** [comment]
I try to make a `PreLoader.efi` patched with your patches.

But the terminal shows something wrong and I haven't got a `PreLoader.efi`.
What I've got is `HashTool.efi`, `HelloWorld.efi`, `KeyTool.efi`, `Loader.efi`, `LockDown.efi`, `ReadVars.efi`, `SetNull.efi`, `ShimReplace.efi`, `UpdateVars.efi` and others with `-signed`.


This is the log,
[output.log](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/files/12189950/output.log)

Could you help to see?

![图片](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/assets/69227436/26f634f0-773d-4db4-a0df-f6a9ac0ca30e)

**Comment by ValdikSS** [comment]
> How do I apply your security bypass patches to chainloader, linux/linuxefi and shim？

Grab patches from here: https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/tree/master/grub-patches
They most probably won't apply cleanly, you'll need to adapt it to newer GRUB version.

>But the terminal shows something wrong 

Zsh tries to `glob()` a file with `.rel.*` name. Use single quotes `'.rel.*'`.

**Comment by 1457384613gh** [comment]
@ValdikSS 
I have used your security bypass patches.
And I write a credit to you.
https://github.com/M-L-P/Yours-UEFI
![image](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/assets/69227436/e659adf1-d339-4235-9338-37520d1498ef)
