### ISSUE TITLE
Quick Question about installing 

### ISSUE THREAD

**Issue by PaleScribbles** [ValdikSS/Super-UEFIinSecureBoot-Disk#24]
Hello, i have been looking a solution to install linux by bypassing secure boot. Can you tell me how to use this exactly? because i thought it requires to put an .iso in /iso/ folder  i.e kali, I'm currently using this with ventoy or should i need to copy files from ./Boot folder into another /Boot folder (in Parrot Os's .iso) and paste them to bypass signature error ? Because i enrolled the certificate via efi and nothing changed at all. I mean, i don't probably know how to use and i really wanted to. Best regards

**Comment by ValdikSS** [comment]
Ventoy already includes SUISBD, you don't need to install this one if you use Ventoy. Make sure you install it with "Secure boot enable" flag.

You don't need to do anything extra to use SUISBD. It hijacks verification process and bypasses it.
