### ISSUE TITLE
Booting SUISDB from Windows bootmanager?

### ISSUE THREAD

**Issue by danboid** [ValdikSS/Super-UEFIinSecureBoot-Disk#29]
We mainly run Windows but we also use LTSP Ubuntu.

With the rapidly approaching end of support of Windows 10, we are moving to Windows 11 which means secure boot will be enabled so we can no longer use grub4dos to boot LTSP via the Wiindows bootmanager.

Unfortunately we have to use Windows bootmanager as the main bootloader and we can't switch to GRUB or refind. Is it possible to boot SUISDB from the Windows bootmanager? 

Would it be necessary to run mokmanager and enroll the key on every boot of SUISDB or does it only need to be done once per machine? I don't suppose this enrolment can be automated?

Thanks

**Comment by ValdikSS** [comment]
grub4dos, the regular legacy one? It's, well, for DOS, not for UEFI. You won't be able to boot it from any UEFI bootloader, including SUISBD.

If you want to run any distro which has its bootloader signed, you don't need to do anything besides adding its bootloader path to Windows loader. It should work with Ubuntu/Debian/Fedora at least.

I can't comment any further as I never tried it, and never worked with Windows close enough.
