### ISSUE TITLE
Silent-UEFIinSecureBoot-Disk

### ISSUE THREAD

**Issue by smopro** [ValdikSS/Super-UEFIinSecureBoot-Disk#3]
```
git clone /home/smopro/ZeroBundle/ZeroNet/data/1KVD7PxZVke1iq4DKb4LNwuiHS4UzEAdAv/silent-uefiinsecureboot-disk.git 
fatal: репозиторий «/home/smopro/ZeroBundle/ZeroNet/data/1KVD7PxZVke1iq4DKb4LNwuiHS4UzEAdAv/silent-uefiinsecureboot-disk.git» не существует

```
Арч линукс, зеро нет Version: 0.6.5 r3862, Python 2.7.11

**Comment by ValdikSS** [comment]
Вероятно, сначала репозиторий нужно загрузить, открыв в браузере.

**Comment by smopro** [comment]
> Вероятно, сначала репозиторий нужно загрузить, открыв в браузере.

Трабла именно в твоем репозитории в зеронет, поэтому его никто и скачать нынче не может.
"Talking to @gitcenter now. He knows the problem and is thinking about a fix right now. This particular git repo uses packed-refs with empty refs folder. Since the refs folder is empty - ZeroNet doesn't publish it (so rather than the folder being empty, the folder simply doesn't exist). Git checks for this refs folder in order to determine whether it's an actual repo. Because of this, it thinks it's not a proper repo."

**Comment by ValdikSS** [comment]
Видимо, проблема проявляется только на старых версиях git. В Fedora 29 с `git version 2.20.1` работает, но на Debian 9 `git version 2.11.0` — нет.
Вообще, это самый обычный bare-репозиторий с packed-refs, который я создал с помощью `git clone --bare. В репозитории нет ничего странного или необычного, я не редактировал его вручную. У меня он работает как через веб-интерфейс Git Center, так и через git, и успешно клонируется, проверил на свежеустановленном ZeroNet.

Пересоздал репозиторий, вручную добавив refs и удалив packet-refs. Попробуйте. Или просто воспользуйтесь более новой версией git.

**Comment by smopro** [comment]
Странно, у меня на арче git version 2.21.0 не работало. Сейчас после переделки все клонировалось той же версией. Спасибо что откликнулся.
