### ISSUE TITLE
Boot from another ext4 partition

### ISSUE THREAD

**Issue by gorru** [ValdikSS/Super-UEFIinSecureBoot-Disk#6]
Hi. I'm trying to boot a customized distro that I made without luck.
I put your image in a usb drive via dd and then added a new partition with gparted.
I then changed the grub.cfg file in order to search the root  filesystem by label to complete boot.

When I start the pc some screen flashes occurs and the a message says that /vmlinux was not found.
pressing a key appears a message that says that both default and fallback entries failed.
Then my grub menu is shown but if I try to go ahead a new /vmlinux was not found message is printed.

Can you help me?
Thanks in advance

**Comment by ValdikSS** [comment]
You need to set proper `root` variable to your disk.
Use `search --set=root …` command or just `set root=(hd…,…)`
https://www.gnu.org/software/grub/manual/grub/html_node/GRUB-only-offers-a-rescue-shell.html

**Comment by gorru** [comment]
it works!
Thank you very much!
