### ISSUE TITLE
Can i overwrite existing grub2 with this to disable secure boot?

### ISSUE THREAD

**Issue by neigga** [ValdikSS/Super-UEFIinSecureBoot-Disk#7]
i have pre-installed ubuntu partition with full root/physical access. can i overwrite existing grub2 files with these to disable secureboot?

**Comment by ValdikSS** [comment]
Yes, you can probably rename your original `bootx64.efi` or `grubx64.efi` to `grubx64_real.efi`, then copy `bootx64.efi` and `grubx64.efi` from the disk, and it should work. But why would you want that? It's easier to either disable Secure Boot or disable validation in Shim (using `mokutil`).
