### ISSUE TITLE
how to remove the .cer from bios?

### ISSUE THREAD

**Issue by QingKongBaiYu** [ValdikSS/Super-UEFIinSecureBoot-Disk#9]
please help. factory bios settings not working.

**Comment by ValdikSS** [comment]
You need to clean the certificate from MokDB UEFI variable, or remove it completely. You can do that with [keytool.efi](https://kojipkgs.fedoraproject.org//packages/efitools/1.9.2/4.fc35/x86_64/efitools-1.9.2-4.fc35.x86_64.rpm) in UEFI for example, or with UEFI shell.
